import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import EnrollModal from "@/components/EnrollModal";
import { EnrollModalProvider } from "@/contexts/EnrollModalContext";
import { Cairo } from "next/font/google";
import { LangProvider } from "@/contexts/LangContext";

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  variable: "--font-cairo",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mudarris Akademiyasi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="uz" className={`${geistSans.variable} ${geistMono.variable} ${cairo.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col bg-white">
        <EnrollModalProvider>
          <LangProvider>
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </LangProvider>
          <EnrollModal />
        </EnrollModalProvider>
      </body>
    </html>
  );
}